image: Ubuntu

stack: jdk 1

branches:
  only:
    - master

build: off

install:
  - java -jar ./artifacts/app-order.jar &

build_script:
  - chmod +x gradlew
  - chmod +x geckodriver
  - ./gradlew test --info -Dselenide.headless=true
